### ISSUE TITLE
rib destroys history on every new session and doesn't read old history

### ISSUE THREAD

**Issue by swrobel** [godfat/rib#12]
When I open rib the second time, I'm pressing :arrow_up: on the keyboard but no history is showing.

![Screen Recording](http://g.recordit.co/d6HyJqaf0H.gif)

```
$ gem list rib

*** LOCAL GEMS ***

rib (1.2.91)
```

Contents of `~/.rib/config.rb`:
`require 'rib/core/history'`

**Comment by godfat** [comment]
I can't reproduce this, could you please try run rib with: `rib -d` so that we could see some debugging messages?

My first guess is that there's some issues with your readline extension. I guess you're on Mac therefore using editline instead. You could also try to build your ruby with readline. To install readline, if you're using Homebrew, you could simply do `brew install readline` and maybe also link it `brew link readline`.

My suggest would be just install ruby via Homebrew though. It has less issues to begin with. `brew install ruby`.

**Comment by swrobel** [comment]
Issue raised with Bond: https://github.com/cldwalker/bond/issues/42

**Comment by godfat** [comment]
Did you get it work? What's your result for this?

    ruby -rreadline -e 'puts Readline::VERSION'

If you're using readline, you should see a number.
Otherwise, you would see `EditLine wrapper`.

On the other hand, did the history work now?

**Comment by swrobel** [comment]
```
$ ruby -rreadline -e 'puts Readline::VERSION'
6.3
```

History is working now, as far as I can tell.

**Comment by godfat** [comment]
Great, thanks for confirming. So I guess indeed history didn't work well with editline.
