### ISSUE TITLE
show-method support?

### ISSUE THREAD

**Issue by penguinwokrs** [godfat/rib#22]
Hi.
Are `show-metod` and` show-source` in pry planned for implementation?
Reference: https://github.com/pry/pry/wiki/Source-browsing

**Comment by godfat** [comment]
No plans at the moment, and it looks like a lot of codes to implement this. On the other hand, I might prefer to open the file at the particular line with an editor though.

I am thinking maybe we could implement a Pry compatible layer, so that we could just use pry plugins? Because it seems there's a lot of interesting features in pry but I don't really see the value implementing everything all over again.

**Comment by penguinwokrs** [comment]
understood.
I will challenge the implementation with a plugin.
