### ISSUE TITLE
Asciicast on rib webpage is broked

### ISSUE THREAD

**Issue by NNBnh** [godfat/rib#25]
![image](https://user-images.githubusercontent.com/43980777/159172185-558ea0f4-3871-4d08-8d92-167d443dee40.png)

**Comment by godfat** [comment]
Thanks for reporting. I'll try to make a new recording.

**Comment by godfat** [comment]
I am trying to update this at https://github.com/lulalala/rib-web/pull/3

**Comment by godfat** [comment]
The whole source was so old that I managed to fixed a few Ruby 3 compatibility issue, but then FFI still crashed due to Ruby C API changes.

I have to install Ruby 2.7 to rebuild the site.

As a future reference, this was the command I tried to rebuild the site:

    ruby-2.7 -S bundle exec gem/ruby/2.7.0/bin/middleman build

I also changed the root directory from `/home/rib-web/rib-web` to `/home/rib-web/rib-web/build` because I don't know how to build at the previous location, and I don't want to just move files.

The new cast is finally on the site.
